### ISSUE TITLE
Shader doesnt work in Galacticraft dimensions

### ISSUE THREAD

**Issue by Njet75** [rre36/glsl_nostalgia#10]
**Describe the bug**
Shader doesnt work in Galacticraft dimensions

**To Reproduce**
Go to Galacticraft dimension

**Expected behavior**
Is there an option to enable dimensions?

**Screenshots**

**Desktop (please complete the following information):**
Operating System:
Graphics Card:
Graphics Driver Version:
Game Version:
OF Version:
CPU:
RAM:
Any Overlay Software running:

**Additional context**

**Comment by rre36** [comment]
Because of the way i set up dimensions only the ones i actually made are supported. However if you know the ID of that dimension you can copy the world0 folder in the shader fiels and rename it to ``world[dimension ID here]`` with the dimension ID.

**Comment by Njet75** [comment]
Thanks for Quick answer :)
I gonna try this method and get back with my result.
/Michael

**Comment by rre36** [comment]
You can delete this part
```
    #if s_cloudType==1
        #if s_cloudStyle==2
            rcloud(returnCol);
        #else
            vcloud(returnCol);
        #endif
    #endif
```
at the bottom of composite.fsh in your dimension folder. Same for
```
       #ifdef s_vc2
            v2cloud(returnCol);
        #endif
```
and 
```
    #if s_cloudType==0
        #if s_cloudStyle==2
            pc_realistic(returnCol);
        #else
            pc_vanilla(returnCol);
        #endif
    #endif
```
in deferred2.fsh. Also delete these lines in composte1.fsh because that also disables them in reflections
```
    #ifdef s_vc2
        v2cloud(skyref, spherevec);
    #endif

    #ifdef s_cloudReflection
        reflect_cloud(skyref, spherevec);
    #endif
```

**Comment by Njet75** [comment]
Worked like a charm.
Now the shader works in Galacticraft dimensions.

/Thanks Michael

**Comment by rre36** [comment]
could you post the dimension id here too? maybe i'll do a roundup on common mod dimensions at some point :p

**Comment by Njet75** [comment]
Of course
Here is the mod dimensions and default dimension id I use.

Galacticraft : Moon Dim-28
                     Mars Dim -29
                     Asteroidbelt -30
                     Venus-31
Twilight Forrest : Dim 7

I also have Lost cities in dimension 111 but cant remember if thats default.

Alien vs Predator mod is two id´s :  DIM_LV223 and DIM_LV426

**Comment by Njet75** [comment]
![sun](https://user-images.githubusercontent.com/8996171/65831512-b5004900-e2ba-11e9-8143-6568bf4f7668.png)
Having a new problem?
Your solution worked fine but the sun and the moon dont render correct.
I Think it have to do with the mod Advanced Rockertry.
Is there a way to completly turn off custom sky?

**Comment by rre36** [comment]
iirc there was some kind of incompatibility between the advanced rocketry and optifine, so idk if it could even work at all there
